package com.mshykhov.jobhunter.infrastructure.materials

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(MaterialEncryptionProperties::class)
class MaterialEncryptionConfig
